// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yudelka_Guillen_P2_Ap1.Api.DAL;

#nullable disable

namespace Yudelka_Guillen_P2_Ap1.Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240304231942_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Shared.Models.Accesorios", b =>
                {
                    b.Property<int>("AccesoriosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccesoriosId");

                    b.ToTable("Acesorios");

                    b.HasData(
                        new
                        {
                            AccesoriosId = 1,
                            Descripcion = "Camara Trasera"
                        },
                        new
                        {
                            AccesoriosId = 2,
                            Descripcion = "Pantalla Interior"
                        },
                        new
                        {
                            AccesoriosId = 3,
                            Descripcion = "Interior en Piel"
                        },
                        new
                        {
                            AccesoriosId = 4,
                            Descripcion = "Sun Roof"
                        },
                        new
                        {
                            AccesoriosId = 5,
                            Descripcion = "Aros de Lujo"
                        });
                });

            modelBuilder.Entity("Shared.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("Gastos")
                        .HasColumnType("REAL");

                    b.HasKey("VehiculoId");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("Shared.Models.VehiculoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccesorioId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.Property<int>("VehicukoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("VehiculoDetalle");
                });

            modelBuilder.Entity("Shared.Models.VehiculoDetalle", b =>
                {
                    b.HasOne("Shared.Models.Vehiculo", null)
                        .WithMany("VehiculoDetalle")
                        .HasForeignKey("VehiculoId");
                });

            modelBuilder.Entity("Shared.Models.Vehiculo", b =>
                {
                    b.Navigation("VehiculoDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
